import type { Metadata } from "next";
import { Archivo } from 'next/font/google';
import "./globals.css";

const archivo = Archivo({
    subsets: ['latin'],
    display: 'swap',
});

// Only include metadata if using Next.js 13+ app directory
export const metadata: Metadata = {
    title: "Matteo Test",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang='en' className={archivo.className}>
            <body>{children}</body>
        </html>
    );
}
