import type { Metadata } from "next";
import { Archivo } from 'next/font/google';
import "./globals.css";

const archivio = Archivo({
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
    title: "Matteo Test",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
		<html lang='en' className={archivio.className}>
			<body>{children}</body>
		</html>
	);
}
